"use client";

import { useMemo, useState } from "react";
import {
  AlertTriangle, ArrowUpRight, BarChart3, Bell, CalendarDays, Check, CheckCircle2,
  ChevronRight, CircleDot, Clock3, Filter, FolderKanban, LayoutDashboard, ListTodo,
  MoreHorizontal, Plus, Search, Settings2, Users, X, Zap
} from "lucide-react";

type Status = "green" | "yellow" | "red";
type View = "dashboard" | "projects" | "demands" | "calendar" | "team" | "reports" | "settings";
type Item = { id:number; title:string; project:string; owner:string; progress:number; due:string; status:Status; priority:string; type:string; tasks:number; subtasks:number };

const seed: Item[] = [
  {id:1,title:"Novo site institucional",project:"Website Institucional",owner:"Marina",progress:78,due:"28/09/2026",status:"green",priority:"Alta",type:"Projeto",tasks:12,subtasks:27},
  {id:2,title:"Campanha Setembro",project:"Marketing",owner:"João",progress:67,due:"26/09/2026",status:"yellow",priority:"Alta",type:"Projeto",tasks:18,subtasks:42},
  {id:3,title:"Dashboard RH",project:"People & Culture",owner:"Camila",progress:91,due:"24/09/2026",status:"green",priority:"Média",type:"Projeto",tasks:9,subtasks:19},
  {id:4,title:"Sistema interno",project:"Operações",owner:"Rafael",progress:43,due:"20/09/2026",status:"red",priority:"Crítica",type:"Projeto",tasks:24,subtasks:63},
  {id:5,title:"Landing Page — Cliente X",project:"Campanha Setembro",owner:"João",progress:45,due:"20/09/2026",status:"red",priority:"Crítica",type:"Task",tasks:1,subtasks:5},
  {id:6,title:"Aprovação de identidade",project:"Branding",owner:"Marina",progress:72,due:"24/09/2026",status:"yellow",priority:"Alta",type:"Demanda",tasks:4,subtasks:11},
  {id:7,title:"Automação CRM",project:"Operações",owner:"Rafael",progress:35,due:"25/09/2026",status:"yellow",priority:"Alta",type:"Task",tasks:1,subtasks:8},
  {id:8,title:"Relatório mensal",project:"DataUp",owner:"Camila",progress:100,due:"22/09/2026",status:"green",priority:"Média",type:"Demanda",tasks:3,subtasks:7}
];
const team = [["Marina","24","21","3","87%"],["João","31","26","5","79%"],["Camila","28","27","1","94%"],["Rafael","22","18","4","82%"]];
const statusMeta = {green:{label:"Normal"},yellow:{label:"Atenção"},red:{label:"Crítico"}};

function StatusPill({status}:{status:Status}) { return <span className={`status ${status}`}><span>●</span>{statusMeta[status].label}</span>; }

export default function Home() {
  const [items,setItems] = useState(seed); const [view,setView] = useState<View>("dashboard"); const [search,setSearch] = useState("");
  const [filter,setFilter] = useState<Status|"all">("all"); const [modal,setModal] = useState(false); const [toast,setToast] = useState("");
  const filtered = useMemo(() => items.filter(i => (filter === "all" || i.status === filter) && `${i.title} ${i.project} ${i.owner}`.toLowerCase().includes(search.toLowerCase())), [items,filter,search]);
  const counts = {green:items.filter(i=>i.status==="green").length,yellow:items.filter(i=>i.status==="yellow").length,red:items.filter(i=>i.status==="red").length};
  const notify = (text:string) => { setToast(text); window.setTimeout(()=>setToast(""),2600); };
  function createItem(e:React.FormEvent<HTMLFormElement>) { e.preventDefault(); const fd=new FormData(e.currentTarget); const item:Item={id:Date.now(),title:String(fd.get("title")),project:String(fd.get("project")),owner:String(fd.get("owner")||"Sem responsável"),progress:0,due:String(fd.get("due")||"30/09/2026"),status:"green",priority:String(fd.get("priority")),type:"Demanda",tasks:0,subtasks:0}; setItems(v=>[item,...v]); setModal(false); notify("Demanda criada com sucesso."); }
  function navigate(next:View) { setView(next); setFilter("all"); }
  const title = view === "dashboard" ? "Visão geral" : view === "team" ? "Equipe" : view === "calendar" ? "Calendário" : view === "reports" ? "Relatórios" : view === "settings" ? "Configurações" : view === "projects" ? "Projetos" : "Demandas";
  return <div className="app">
    <aside className="sidebar"><div className="brand"><div className="brandMark">P</div><div><b>Pulse</b><small>Project Operations</small></div></div><nav>{([["dashboard",LayoutDashboard,"Dashboard"],["projects",FolderKanban,"Projetos"],["demands",ListTodo,"Demandas"],["calendar",CalendarDays,"Calendário"],["team",Users,"Equipe"],["reports",BarChart3,"Relatórios"]] as const).map(([key,Icon,label])=><button key={key} className={view===key?"active":""} onClick={()=>navigate(key)}><Icon/>{label}</button>)}</nav><div className="sidebarBottom"><button className={view==="settings"?"active":""} onClick={()=>navigate("settings")}><Settings2/>Configurações</button><div className="profile"><div className="avatar">WB</div><div><b>Wanderson</b><small>Administrador</small></div><MoreHorizontal size={17}/></div></div></aside>
    <main><header className="topbar"><div className="crumb"><span>Workspace</span><ChevronRight size={15}/><b>{title}</b></div><div className="topActions"><div className="search"><Search size={17}/><input aria-label="Buscar" placeholder="Buscar projetos, demandas..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button onClick={()=>setSearch("")}><X size={14}/></button>}</div><button className="iconBtn" aria-label="Notificações" onClick={()=>notify("Você está em dia com as notificações.")}><Bell size={18}/><i/></button><button className="primary" onClick={()=>setModal(true)}><Plus size={17}/> Nova demanda</button></div></header>
      {view==="dashboard"&&<Dashboard items={filtered} counts={counts} filter={filter} setFilter={setFilter} onNew={()=>setModal(true)} onNavigate={navigate}/>} {view==="projects"&&<ListView title="Projetos" subtitle="Acompanhe prazo, progresso e saúde de cada projeto." items={filtered} filter={filter} setFilter={setFilter} onNew={()=>setModal(true)} onRemove={id=>setItems(v=>v.filter(x=>x.id!==id))}/>} {view==="demands"&&<ListView title="Demandas" subtitle="Todas as demandas e seus respectivos níveis de risco." items={filtered} filter={filter} setFilter={setFilter} onNew={()=>setModal(true)} onRemove={id=>setItems(v=>v.filter(x=>x.id!==id))}/>} {view==="team"&&<Team/>} {view==="calendar"&&<Calendar items={items}/>} {view==="reports"&&<Reports items={items}/>} {view==="settings"&&<Settings notify={notify}/>}</main>
    {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><form className="modal" onSubmit={createItem}><div className="modalHead"><div><b>Nova demanda</b><span>Cadastre uma demanda para acompanhar prazo e execução.</span></div><button type="button" className="close" onClick={()=>setModal(false)}><X/></button></div><label>Nome da demanda<input name="title" required placeholder="Ex.: Criar campanha de lançamento"/></label><div className="two"><label>Projeto<input name="project" required placeholder="Ex.: Marketing"/></label><label>Responsável<input name="owner" placeholder="Ex.: Marina"/></label></div><div className="two"><label>Prazo<input name="due" placeholder="30/09/2026"/></label><label>Prioridade<select name="priority"><option>Baixa</option><option>Média</option><option>Alta</option><option>Crítica</option></select></label></div><div className="modalActions"><button type="button" className="secondary" onClick={()=>setModal(false)}>Cancelar</button><button className="primary">Criar demanda</button></div></form></div>}{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
  </div>
}

function Dashboard({items,counts,filter,setFilter,onNew,onNavigate}:{items:Item[];counts:Record<Status,number>;filter:Status|"all";setFilter:(x:Status|"all")=>void;onNew:()=>void;onNavigate:(x:View)=>void}) { const health=Math.round((counts.green*100+counts.yellow*55+counts.red*15)/Math.max(1,counts.green+counts.yellow+counts.red)); return <section className="content"><div className="hero"><div><span className="eyebrow">CENTRAL DE OPERAÇÕES</span><h1>Bom dia, Wanderson.</h1><p>Veja em segundos o que está saudável, em risco e o que precisa de intervenção.</p></div><button className="secondary" onClick={onNew}><Plus size={17}/> Criar demanda</button></div><div className="cards"><Metric icon={<FolderKanban/>} label="Projetos ativos" value="12" note="+2 esta semana"/><Metric icon={<ListTodo/>} label="Demandas abertas" value="47" note="8 vencem em 7 dias"/><Metric icon={<Clock3/>} label="Tasks em atraso" value="14" note="−3 desde ontem" danger/><Metric icon={<Zap/>} label="Saúde da operação" value={`${health}%`} note="baseado no risco atual"/></div><div className="health"><div className="sectionTitle"><div><h2>Saúde da operação</h2><span>O semáforo considera prazo, progresso e bloqueios.</span></div><Filter size={18}/></div><div className="traffic">{(["green","yellow","red"] as Status[]).map(s=><button key={s} className={`trafficCard ${s} ${filter===s?"selected":""}`} onClick={()=>setFilter(filter===s?"all":s)}><div className="trafficTop"><span className={`bigDot ${s}`}/><b>{statusMeta[s].label}</b><span className="count">{counts[s]}</span></div><span>{s==="green"?"Dentro do prazo":s==="yellow"?"Próximo do atraso":"Ação necessária"}</span></button>)}</div></div><div className="grid2"><div className="panel"><div className="sectionTitle"><div><h2>Projetos em acompanhamento</h2><span>Visão rápida de progresso e prazo.</span></div><button className="linkBtn" onClick={()=>onNavigate("projects")}>Ver todos <ArrowUpRight size={15}/></button></div><div className="projectList">{items.filter(x=>x.type==="Projeto").slice(0,5).map(x=><ProjectRow key={x.id} x={x}/>)}</div></div><div className="panel"><div className="sectionTitle"><div><h2>Atenção necessária</h2><span>Itens que precisam de intervenção.</span></div><AlertTriangle size={18}/></div><div className="attention">{items.filter(x=>x.status!=="green").slice(0,5).map(x=><div className="attentionRow" key={x.id}><span className={`tinyDot ${x.status}`}/><div><b>{x.title}</b><small>{x.owner} · {x.project}</small></div><StatusPill status={x.status}/></div>)}</div></div></div><div className="panel"><div className="sectionTitle"><div><h2>Produtividade do time</h2><span>Indicadores operacionais do período atual.</span></div><button className="linkBtn" onClick={()=>onNavigate("reports")}>Relatório completo <ArrowUpRight size={15}/></button></div><TeamTable/></div></section> }
function Metric({icon,label,value,note,danger}:{icon:React.ReactNode;label:string;value:string;note:string;danger?:boolean}) { return <div className="metric"><div className="metricIcon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small className={danger?"danger":""}>{note}</small></div></div> }
function ProjectRow({x}:{x:Item}) { return <div className="projectRow"><div className={`projectIcon ${x.status}`}><FolderKanban size={17}/></div><div className="projectMain"><div><b>{x.title}</b><StatusPill status={x.status}/></div><div className="progress"><i style={{width:`${x.progress}%`}}/></div><small>{x.progress}% concluído · prazo {x.due}</small></div><div className="owner">{x.owner}</div><ChevronRight size={16}/></div> }
function ListView({title,subtitle,items,filter,setFilter,onNew,onRemove}:{title:string;subtitle:string;items:Item[];filter:Status|"all";setFilter:(x:Status|"all")=>void;onNew:()=>void;onRemove:(id:number)=>void}) { return <section className="content"><div className="hero"><div><span className="eyebrow">GESTÃO</span><h1>{title}</h1><p>{subtitle}</p></div><button className="primary" onClick={onNew}><Plus size={17}/> Nova demanda</button></div><div className="toolbar"><div className="chips"><button className={filter==="all"?"chip active":"chip"} onClick={()=>setFilter("all")}>Todos</button>{(["green","yellow","red"] as Status[]).map(s=><button key={s} className={filter===s?"chip active":"chip"} onClick={()=>setFilter(s)}><span className={`tinyDot ${s}`}/>{statusMeta[s].label}</button>)}</div><span>{items.length} itens</span></div><div className="tablePanel"><table><thead><tr><th>Item</th><th>Projeto</th><th>Responsável</th><th>Progresso</th><th>Prazo</th><th>Saúde</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.title}</b><small>{x.type} · {x.priority}</small></td><td>{x.project}</td><td>{x.owner}</td><td><div className="tableProgress"><i style={{width:`${x.progress}%`}}/><span>{x.progress}%</span></div></td><td>{x.due}</td><td><StatusPill status={x.status}/></td><td><button className="rowAction" aria-label={`Remover ${x.title}`} onClick={()=>onRemove(x.id)}><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table>{!items.length&&<div className="empty"><CircleDot size={24}/>Nenhum item encontrado.</div>}</div></section> }
function Team(){return <section className="content"><div className="hero"><div><span className="eyebrow">PESSOAS</span><h1>Equipe</h1><p>Acompanhe carga, entregas e cumprimento de prazo.</p></div></div><div className="cards"><Metric icon={<Users/>} label="Pessoas ativas" value="14" note="4 com maior carga"/><Metric icon={<CheckCircle2/>} label="Entregas no prazo" value="86%" note="+4% no período"/><Metric icon={<Clock3/>} label="Tempo médio" value="2,8d" note="−0,4d vs. anterior"/><Metric icon={<AlertTriangle/>} label="Itens bloqueados" value="6" note="2 críticos" danger/></div><div className="panel"><div className="sectionTitle"><div><h2>Performance operacional</h2><span>Não é apenas volume: considera prazo, execução e retrabalho.</span></div></div><TeamTable/></div></section> }
function TeamTable(){return (<div className="teamTable"><div className="teamHead"><span>Pessoa</span><span>Concluídas</span><span>No prazo</span><span>Atrasadas</span><span>Eficiência</span></div>{team.map((t)=>(<div className="teamRow" key={t[0]}><div className="person"><div className="avatar sm">{t[0].slice(0,2).toUpperCase()}</div><b>{t[0]}</b></div><span>{t[1]}</span><span>{t[2]}</span><span className="dangerText">{t[3]}</span><strong>{t[4]}</strong></div>))}</div>)}
function Calendar({items}:{items:Item[]}){return <section className="content"><div className="hero"><div><span className="eyebrow">PLANEJAMENTO</span><h1>Calendário</h1><p>Visualize prazos e organize as próximas entregas.</p></div></div><div className="panel calendarPanel"><div className="calendarHead"><button className="secondary">‹</button><h2>Setembro 2026</h2><button className="secondary">›</button></div><div className="week">{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map(d=><b key={d}>{d}</b>)}</div><div className="calendarGrid">{Array.from({length:30},(_,i)=>{const day=i+1;const dayItems=items.filter(x=>Number(x.due.slice(0,2))===day);return <div className={`day ${day===23?"today":""}`} key={day}><span>{day}</span>{dayItems.slice(0,2).map(x=><small className={x.status} key={x.id}>{x.title}</small>)}</div>})}</div></div></section>}
function Reports({items}:{items:Item[]}){const done=items.filter(x=>x.progress===100).length; const average=Math.round(items.reduce((a,x)=>a+x.progress,0)/items.length); return <section className="content"><div className="hero"><div><span className="eyebrow">ANÁLISE</span><h1>Relatórios</h1><p>Indicadores para orientar decisões e priorização operacional.</p></div><button className="secondary" onClick={()=>window.print()}><ArrowUpRight size={17}/> Exportar relatório</button></div><div className="reportGrid"><div className="panel reportCard"><span>Conclusão média</span><strong>{average}%</strong><div className="bar"><i style={{width:"74%"}} /></div><small>+8% comparado ao período anterior</small></div><div className="panel reportCard"><span>Entregas concluídas</span><strong>{done}</strong><div className="bar"><i style={{width:"62%"}} /></div><small>de {items.length} itens acompanhados</small></div><div className="panel reportCard"><span>Risco operacional</span><strong>{items.filter(x=>x.status!=="green").length} itens</strong><div className="bar redbar"><i style={{width:"38%"}} /></div><small>Priorize os itens críticos primeiro</small></div></div><div className="panel"><div className="sectionTitle"><div><h2>Distribuição por status</h2><span>Panorama consolidado da operação.</span></div></div><div className="reportBars">{(["green","yellow","red"] as Status[]).map(s=>(<div key={s}><div><b>{statusMeta[s].label}</b><span>{items.filter(x=>x.status===s).length} itens</span></div><div className="bar"><i className={s} style={{width:`${items.filter(x=>x.status===s).length/items.length*100}%`}} /></div></div>))}</div></div></section>}
function Settings({notify}:{notify:(text:string)=>void}){return <section className="content"><div className="hero"><div><span className="eyebrow">WORKSPACE</span><h1>Configurações</h1><p>Personalize o workspace e as preferências da operação.</p></div></div><div className="settingsGrid"><div className="panel settingsCard"><Settings2/><h2>Preferências gerais</h2><label>Nome do workspace<input defaultValue="Pulse Operations"/></label><label>Fuso horário<select defaultValue="America/Sao_Paulo"><option value="America/Sao_Paulo">(GMT-03:00) São Paulo</option><option>UTC</option></select></label><button className="primary" onClick={()=>notify("Preferências salvas com sucesso.")}><Check size={16}/> Salvar alterações</button></div><div className="panel settingsCard"><Bell/><h2>Notificações</h2><label className="toggle"><input type="checkbox" defaultChecked/> Alertas de prazo</label><label className="toggle"><input type="checkbox" defaultChecked/> Resumo semanal</label><label className="toggle"><input type="checkbox"/> Atualizações da equipe</label></div></div></section>}
